spring.application.name=springsecurity

spring.java.version=${java.version}
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true

# Security configuration (uncomment to enable basic authentication)
#spring.security.user.name = admin
#spring.security.user.password = admin

# JWT configuration
spring.app.jwt.secret=myVeryStrongSecretKeyForJwtAuthentication2026
spring.app.jwt.expiration=3600000
spring.app.jwt.issuer=your_jwt_issuer
spring.app.jwt.audience=your_jwt_audience
spring.app.jwt.signing-algorithm=HS256
spring.app.jwt.token-prefix=Bearer
spring.app.jwt.header-name=Authorization

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.org.springframework.security=INFO
logging.level.com.webshopping=INFO
logging.file.name=log/${spring.application.name}.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%15.15t] %-40.40logger{39} : %m%n%wEx

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%clr(${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){red}